FROM oracle/graalvm-ce:20.3.0-java11 as BUILDER

ENV GRAALVM_HOME=$JAVA_HOME

RUN gu install native-image \
    && gu install ruby \
    && gu install python \
    && gu install r \
    && curl -O https://download.clojure.org/install/linux-install-1.10.1.727.sh \
    && chmod +x linux-install-1.10.1.727.sh \
    && ./linux-install-1.10.1.727.sh \
    && rm linux-install-1.10.1.727.sh

RUN mkdir /root/.gitlibs

WORKDIR /usr/src/app
COPY deps.edn /usr/src/app/

RUN clojure -P -M:test

COPY . /usr/src/app
